services:
  web:
    build: .
    image: foto-hosting:1.0.2
    container_name: foto-hosting_fin-web
    volumes:
      - .:/app
      - ./images:/app/images
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped

  nginx:
    image: nginx:1.28
    container_name: foto-hosting_fin_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/app/images:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  images_volume:
  logs_volume: